stages:
  - Backend Static Analysis
  - Frontend Static Analysis
  

eslint:
  image: cypress/base:10
  stage: Frontend Static Analysis
  script:
  - node --version
  - cd frontend
  - npm ci
  - npm install
  - ./node_modules/.bin/eslint "**/*.tsx"

flake8:
  image: python:3.7
  stage: Backend Static Analysis
  script:
  - python -V
  - pip -V
  - pip install -r backend/requirements.txt
  - flake8 --max-line-length=120 --per-file-ignores='backend/populate_database.py:E402' backend

