stages:
- backend
- frontend

backend:
  stage: backend
  image: python:3.7
  script:
  - pip install -r backend/requirements.txt
  - flake8 backend
  - coverage run --branch backend/manage.py test backend
  - coverage report --fail-under=70

frontend:
  stage: frontend
  image: cypress/base:10
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - frontend/node_modules/
      - /root/.cache/Cypress
  script:
  - cd frontend
  - npm ci
  - ./node_modules/.bin/eslint "**/*.tsx"
  - npm run start-with-coverage
  - npm test
  - npx nyc report --reporter=text-summary --check-coverage=true
